-- Create basic roles
CREATE ROLE web_anon NOLOGIN;
CREATE ROLE authenticated NOLOGIN;
CREATE ROLE admin_user NOLOGIN;
CREATE ROLE regular_user NOLOGIN;

-- Create authenticator role (used by PostgREST)
CREATE ROLE authenticator NOINHERIT LOGIN PASSWORD 'workshop_auth_pass';

-- Grant role memberships
GRANT web_anon TO authenticator;
GRANT authenticated TO authenticator;
GRANT admin_user TO authenticator;
GRANT regular_user TO authenticator;

-- Create auth schema
CREATE SCHEMA IF NOT EXISTS auth;

-- Install required extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pgjwt;
CREATE EXTENSION IF NOT EXISTS postgis;

-- Create users table in auth schema
CREATE TABLE auth.users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'regular_user',
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Create basic sample table
CREATE TABLE public.todos (
  id int primary key generated by default as identity,
  done boolean not null default false,
  task text not null,
  due timestamptz
);

-- Create workshops table
CREATE TABLE public.workshops (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    location VARCHAR(255),
    max_participants INTEGER DEFAULT 50,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Create participants table
CREATE TABLE public.participants (
    id SERIAL PRIMARY KEY,
    workshop_id INTEGER REFERENCES workshops(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    registered_at TIMESTAMP DEFAULT NOW()
);

-- Create locations table with PostGIS geometry
CREATE TABLE public.locations (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    geometry GEOMETRY(POINT, 4326),
    created_by INTEGER REFERENCES auth.users(id),
    created_at TIMESTAMP DEFAULT NOW()
);

-- Insert dummy workshops
INSERT INTO public.workshops (title, description, start_date, end_date, location, max_participants) VALUES
('PostgreSQL Basics', 'Learn the fundamentals of PostgreSQL', '2024-02-01 09:00:00', '2024-02-01 17:00:00', 'Boston, MA', 30),
('PostGIS Workshop', 'Spatial data with PostGIS', '2024-02-15 09:00:00', '2024-02-15 17:00:00', 'Cambridge, MA', 25),
('PostgREST API Development', 'Build APIs with PostgREST', '2024-03-01 09:00:00', '2024-03-01 17:00:00', 'New York, NY', 40);

-- Insert dummy participants
INSERT INTO public.participants (workshop_id, name, email) VALUES
(1, 'John Doe', 'john@example.com'),
(1, 'Jane Smith', 'jane@example.com'),
(2, 'Bob Johnson', 'bob@example.com'),
(3, 'Alice Brown', 'alice@example.com');

-- Insert sample locations (Boston area)
INSERT INTO public.locations (name, description, geometry) VALUES
('Boston Common', 'Historic public park', ST_GeomFromText('POINT(-71.0656 42.3548)', 4326)),
('MIT Campus', 'Massachusetts Institute of Technology', ST_GeomFromText('POINT(-71.0942 42.3601)', 4326)),
('Harvard University', 'Harvard University campus', ST_GeomFromText('POINT(-71.1167 42.3770)', 4326));

-- Grant basic permissions
GRANT USAGE ON SCHEMA public TO web_anon, authenticated, admin_user, regular_user;
GRANT USAGE ON SCHEMA auth TO authenticated, admin_user;
GRANT SELECT ON public.todos TO web_anon;
GRANT SELECT ON public.workshops TO web_anon;
GRANT SELECT ON public.participants TO web_anon;
GRANT SELECT ON public.locations TO web_anon;
GRANT INSERT ON public.locations TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.locations TO authenticated;
